import React from "react";

export default function Footer() {
  return (
    <footer className="footer">
      <div className="footer-logo">StyleWidMe</div>

      <p className="footer-tag">
        A small, human-made shop — every listing written and styled by a real person,
        not generated by a bot. Thank you for supporting handmade care in a digital world.
      </p>

      <div className="footer-links">
        <a href="#">About</a>
        <a href="#">Shipping</a>
        <a href="#">Returns</a>
        <a href="#">Contact</a>
        <a href="#">Instagram</a>
      </div>

      <div className="footer-made">
        © {new Date().getFullYear()} StyleWidMe — 100% human-made, with a bow on top 🎀
      </div>
    </footer>
  );
}
